"""Write spear/machine.env from what this machine already has.

machine.env is this machine's local configuration -- where the session
accumulates, where a deployment's private content lives, which host embeds a
standard and with which pinned model -- and it was written by hand, with no
template, from reading the docs. Every value in it can be found instead:

    state          SPEAR_STATE_DIR, else the workstation default
    private tree   a sibling spear-private/ holding rules.d, skills, benches
    embedding      the model active-embedder.conf names, the host
                   active-embed-remote.conf names, and the revision BOTH
                   ends' Hub caches resolve `main` to

A revision the two ends disagree on is refused rather than written: vectors
would then be stamped with a revision the host did not use.

What is written below the LOCAL marker is the operator's own and is carried
over unchanged, so regenerating never costs a hand-made setting.
"""

from __future__ import annotations

import argparse
import difflib
import os
import sys
from datetime import datetime
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent
REPO = APP_DIR.parent
TARGET = APP_DIR / "machine.env"

DEFAULT_STATE = "$HOME/.local/state/spear"
LOCAL_MARKER = "# --- local additions: kept as they are by spear-configure ---"
GENERATED = "# Generated by scripts/spear-configure"

#: The private tree's resource directories, and the variable each sets.
PRIVATE_DIRS = (("SPEAR_RULES_DIR", "rules.d"), ("SPEAR_SKILLS_DIR", "skills"),
                ("SPEAR_BENCH_DIR", "benches"))


class ConfigureError(RuntimeError):
    pass


class HostUnreachable(ConfigureError):
    """The embedding host did not answer: nothing is known about its cache."""


def local_revision(model: str, env=None) -> str | None:
    """What `main` resolves to for `model` in this machine's Hub cache."""
    import embedding

    path = (Path(embedding.hub_cache_dir(env))
            / ("models--" + model.replace("/", "--")) / "refs" / "main")

    try:
        return path.read_text().strip() or None
    except OSError:
        return None


def detect_private(private: str | None) -> Path | None:
    """The private tree: as named, else a sibling spear-private/, else none."""
    if private == "":
        return None

    candidate = Path(private).expanduser() if private else REPO.parent / "spear-private"

    if any((candidate / name).is_dir() for _, name in PRIVATE_DIRS):
        return candidate.resolve()

    if private:
        raise ConfigureError(f"{candidate} holds none of rules.d, skills, benches")

    return None


def detect_embedding(remote_revision=None, *, verify=True) -> dict | None:
    """Model, pinned revision and host, or None when no host is configured.

    `remote_revision(model, target)` is injectable for tests; it asks the host.
    With verify=False the host is not asked, and the result says so.
    """
    import embedding

    target = embedding.remote_target()

    if not target:
        return None

    model = embedding.active_model()
    here = local_revision(model)

    if here is None:
        raise ConfigureError(
            f"{model} is not in this machine's Hub cache ({embedding.hub_cache_dir()}); "
            f"queries embed here, so it must be")

    if not verify:
        return {"model": model, "revision": here, "target": target,
                "verified": False}

    if remote_revision is None:
        from standard_vector_index import remote_model_revision as remote_revision

    try:
        there = remote_revision(model, target)
    except RuntimeError as exc:
        raise HostUnreachable(f"{exc} -- connect to it (VPN?) or pass --no-embed") from None

    if there != here:
        raise ConfigureError(
            f"{model} resolves to {here} here and to {there or 'nothing'} on "
            f"{target}; the vectors would not match the revision they are "
            f"stamped with. Align the two caches, then run this again")

    return {"model": model, "revision": here, "target": target, "verified": True}


def render(state: str, private: Path | None, embed: dict | None,
           local: str = "", now: str | None = None) -> str:
    now = now or datetime.now().isoformat(timespec="seconds")
    lines = [
        f"{GENERATED} on {now}.",
        "# This machine's local configuration, read by spear-chat, spear-corpus and",
        "# scripts/docker/build.sh. Not tracked. Regenerate it rather than edit it;",
        "# put hand-made settings below the local-additions marker at the end.",
        "",
        "# Where sessions accumulate: history, memories, audit, the standard store.",
        f'export SPEAR_STATE_DIR="{state}"',
        "",
    ]

    if private is not None:
        lines.append(f"# The deployment's own content, from {private}.")

        for var, name in PRIVATE_DIRS:
            if (private / name).is_dir():
                lines.append(f"export {var}={private / name}")

        engagement = private / "engagement.env"

        if engagement.is_file():
            lines.append(f"[ -r {engagement} ] && . {engagement}")

        lines.append("")
    else:
        lines += ["# No private tree: rules, skills and benches are the in-tree ones.", ""]

    if embed is not None:
        lines += [
            "# Document embedding for normative standards, on the GPU host. The",
            "# revision is what both ends' Hub caches resolve `main` to. A PUBLIC",
            "# standard is embedded there; a licensed one never leaves this machine",
            "# unless an ingest/rebuild passes --allow-offload.",
            f"export SPEAR_STANDARD_EMBED_MODEL={embed['model']}",
            f"export SPEAR_STANDARD_EMBED_REVISION={embed['revision']}",
            f"export SPEAR_STANDARD_EMBED_REMOTE={embed['target']}",
            "",
        ]
    else:
        lines += ["# No embedding host: standards are searched lexically.", ""]

    lines += [
        "# Retrieval mode and structural completion are set per document",
        "# (/standard retrieval), not here: exported, they would override every",
        "# document for every session.",
        "",
        LOCAL_MARKER,
    ]

    if local.strip():
        lines.append(local.strip("\n"))

    return "\n".join(lines) + "\n"


def split_local(text: str) -> str:
    """What an existing file holds below the marker."""
    if LOCAL_MARKER not in text:
        return ""

    return text.split(LOCAL_MARKER, 1)[1].strip("\n")


def _comparable(text: str) -> list[str]:
    """Lines to compare, without the generation timestamp."""
    return [line for line in text.splitlines() if not line.startswith(GENERATED)]


def main(argv=None, *, remote_revision=None, stdin=None) -> int:
    ap = argparse.ArgumentParser(
        prog="spear-configure",
        description="Write spear/machine.env from what this machine has.")
    ap.add_argument("--check", action="store_true",
                    help="say whether machine.env still matches; write nothing")
    ap.add_argument("--yes", action="store_true",
                    help="replace a differing machine.env without asking")
    ap.add_argument("--private", metavar="DIR",
                    help="the private tree (default: a sibling spear-private/)")
    ap.add_argument("--no-private", action="store_true",
                    help="configure without a private tree")
    ap.add_argument("--state", metavar="DIR",
                    help=f"session state directory (default: {DEFAULT_STATE})")
    ap.add_argument("--no-embed", action="store_true",
                    help="leave the embedding host out")
    ap.add_argument("--output", metavar="FILE", default=str(TARGET))
    args = ap.parse_args(argv)
    stdin = stdin or sys.stdin
    target = Path(args.output)

    try:
        private = detect_private("" if args.no_private else args.private)

        try:
            embed = None if args.no_embed else detect_embedding(remote_revision)
        except HostUnreachable as exc:
            # A check can still compare everything else, and this machine's
            # own revision; writing cannot pin one the host never confirmed.
            if not args.check:
                raise

            print(f"   !! {exc}", file=sys.stderr)
            embed = detect_embedding(verify=False)
    except ConfigureError as exc:
        print(f"spear-configure: {exc}", file=sys.stderr)
        return 2

    existing = target.read_text() if target.exists() else None
    state = args.state or os.environ.get("SPEAR_STATE_DIR") or DEFAULT_STATE
    text = render(state, private, embed, split_local(existing or ""))

    print(f"   state     {state}")
    print(f"   private   {private or '(none: in-tree rules, skills, benches)'}")
    print("   embedding " + (f"{embed['model']}@{embed['revision'][:12]} on {embed['target']}"
                            + ("" if embed["verified"] else
                               "  (this machine's cache only: host not asked)")
                            if embed else "(none: lexical search only)"))

    if existing is not None and _comparable(existing) == _comparable(text):
        print(f"{target} is up to date.")
        return 0

    diff = "".join(difflib.unified_diff(
        (existing or "").splitlines(keepends=True), text.splitlines(keepends=True),
        f"{target} (current)", f"{target} (generated)"))

    if args.check:
        print(diff or f"{target} does not exist.")
        return 1

    if existing is not None:
        # Written once by hand, a file holds what nothing here can derive;
        # the diff is the only place that shows what regenerating would drop.
        print(diff)

        if not args.yes:
            if not stdin.isatty():
                print("spear-configure: machine.env differs; rerun with --yes to "
                      "replace it", file=sys.stderr)
                return 1

            print("Replace it? The current file is kept as machine.env.bak [y/N] ",
                  end="", flush=True)

            if stdin.readline().strip().lower() not in {"y", "yes", "o", "oui"}:
                print("Left as it is.")
                return 1

        target.with_name(target.name + ".bak").write_text(existing)

    target.write_text(text)
    print(f"Wrote {target}.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
