#!/bin/bash
# Print the spear-inference unit, ready to install, on stdout.
#
#     render-unit.sh --user
#     render-unit.sh --system --account NAME [--home DIR] [--log FILE]
#
# --user prints the template unchanged: under a user manager %h is the
# account's home and the journal is the account's journal.
#
# --system makes the three adaptations a system unit needs, and only those:
#   User=/Group=     a system unit runs as root unless told otherwise
#   %h -> the home   under pid 1, %h is root's home, not the account's
#   WantedBy=        multi-user.target, the system manager's boot target
# --log optionally sends the output to a file instead of the journal, for a
# deployment whose operators already tail one.
#
# It writes nothing. Installing is the operator's act, and needs root:
#
#     server/inference/render-unit.sh --system --account svc \
#         | sudo tee /etc/systemd/system/spear-inference.service >/dev/null
#     sudo systemctl daemon-reload
#     sudo systemctl enable --now spear-inference
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
TEMPLATE="$HERE/spear-inference.service"
MODE="" ACCOUNT="" HOMEDIR="" LOG=""

while [ $# -gt 0 ]; do
    case "$1" in
        --user)    MODE=user; shift ;;
        --system)  MODE=system; shift ;;
        --account) ACCOUNT="$2"; shift 2 ;;
        --home)    HOMEDIR="$2"; shift 2 ;;
        --log)     LOG="$2"; shift 2 ;;
        -h|--help) sed -n '2,23p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "render-unit.sh: unknown argument: $1" >&2; exit 64 ;;
    esac
done

case "$MODE" in
    user)
        exec cat "$TEMPLATE" ;;
    system) ;;
    *) echo "render-unit.sh: say --user or --system" >&2; exit 64 ;;
esac

[ -n "$ACCOUNT" ] || { echo "render-unit.sh: --system needs --account" >&2; exit 64; }
if [ -z "$HOMEDIR" ]; then
    HOMEDIR="$(getent passwd "$ACCOUNT" | cut -d: -f6)"
    [ -n "$HOMEDIR" ] || { echo "render-unit.sh: no account '$ACCOUNT'; pass --home" >&2; exit 64; }
fi
case "$HOMEDIR" in /*) ;; *) echo "render-unit.sh: --home must be absolute" >&2; exit 64 ;; esac

echo "# INSTALLED SYSTEM UNIT -- generated by server/inference/render-unit.sh"
echo "# from spear-inference.service; regenerate rather than edit."
echo
awk -v acct="$ACCOUNT" -v home="$HOMEDIR" -v logfile="$LOG" '
    !/^#/             { gsub(/%h/, home) }
    /^Type=exec$/     { print; print ""; print "User=" acct; print "Group=" acct; next }
    /^StandardOutput=/ && logfile != "" { print "StandardOutput=append:" logfile; next }
    /^StandardError=/  && logfile != "" { print "StandardError=append:" logfile; next }
    /^WantedBy=/      { print "WantedBy=multi-user.target"; next }
    { print }
' "$TEMPLATE"
